### ISSUE TITLE
Event not firing on Android

### ISSUE THREAD

**Issue by H0rst** [nordnet/cordova-universal-links-plugin#34] opened 2016-01-15 11:14 UTC
The universal Links event is not firing on Android with plugin V1.1.

The app was done before with plugin V 1.0 and `addEventlistner`. Because index.html i had to add the `addEventlistener` at the beginning of `index.html`. It has worked.
With V1.1 i tried `universalLinks.subscribe(null, function(){alert('alive')});` in `onDeviceReady`. When tappnig on a link in Chrome i can start the app. But the event is never fired.

**Comment by nikDemyankov** [comment] 2016-01-15 11:22
Maybe Cordova didn't actually update the plugin? Try to run:

```
cordova clean
cordova prepare
cordova build
```

Or reinstall the plugin.

Just created a new app:

```
cordova create TestApp
cd TestApp
cordova platform add android
cordova plugin add cordova-universal-links-plugin
```

Then added the following to the config.xml:

``` xml
<universal-links>
    <host name="testapp.com">
        <path url="/test/*" />
    </host>
</universal-links>
```

And in index.js:

``` js
onDeviceReady: function() {
        app.receivedEvent('deviceready');
        universalLinks.subscribe(null, function() {
          alert('Launched by event');
        });
    },
```

Then `cordova run android`, close it and:

```
adb shell am start -W -a android.intent.action.VIEW -d "http://testapp.com/test/path" io.cordova.hellocordova
```

And I get the alert message.

**Comment by H0rst** [comment] 2016-01-15 12:12
I can confirm, that it works with a new app. But not with the old one. I have removed the plugin and reinstalled it. I checked the files in `platforms\android\src\com\nordnetab\cordova\ul`. They are all new.

**Comment by nikDemyankov** [comment] 2016-01-15 12:37
Can you share your `<universal-links>` content from `config.xml`? Or something similar to what you have in it.

**Comment by H0rst** [comment] 2016-01-15 13:28
I have added some debugging code to `UniversalLinksPlugin.java`:

```
    private void tryToConsumeEvent() {
Log.d("UniversalLinks", "tryToConsumeEvent");
        if (subscribers.size() == 0 || storedMessage == null) {
Log.d("UniversalLinks", "return");
            return;
        }
Log.d("UniversalLinks", "consume");

        final String storedEventName = storedMessage.getEventName();
Log.d("UniversalLinks", "storedEventName "+storedEventName);
        final Set<Map.Entry<String, CallbackContext>> subscribersSet = subscribers.entrySet();
        for (Map.Entry<String, CallbackContext> subscriber : subscribersSet) {
            final String eventName = subscriber.getKey();
Log.d("UniversalLinks", "eventName "+eventName);
            if (eventName.equals(storedEventName)) {
Log.d("UniversalLinks", "sendMessageToJs");
                sendMessageToJs(storedMessage, subscriber.getValue());
                storedMessage = null;
                break;
            }
        }
    }
```

When i try i get this output:

```
01-15 14:03:51.001: D/UniversalLinks(28299): tryToConsumeEvent
01-15 14:03:51.001: D/UniversalLinks(28299): consume
01-15 14:03:51.001: D/UniversalLinks(28299): storedEventName ULOpen
01-15 14:03:51.001: D/UniversalLinks(28299): eventName didLaunchAppFromLink
```

In `config.xml` i use

```
    <universal-links>
        <host name="www.blutdruckdaten.de" scheme="https">
            <path event="ULOpen" url="/lexikon.html" />
            <path event="ULOpen" url="/lexikon/*" />
            <path event="ULOpen" url="/chk*" />
            <path event="ULOpen" url="/del*" />
            <path event="ULOpen" url="/news.html" />
            <path event="ULOpen" url="/newsarchiv.html" />
            <path event="ULOpen" url="/news-en.html" />
            <path event="ULOpen" url="/newsarchive.html" />
        </host>
    </universal-links>
```

I have searched for `didLaunchAppFromLink` in your code and found it as default string. I have tried to replace it wth `ULOpen`, but i get the same result. I am not familiar with Java.

**Comment by H0rst** [comment] 2016-01-15 13:57
I have replaced the text `didLaunchAppFromLink` in all your code with `ULOpen`. In this case it works.

**Comment by nikDemyankov** [comment] 2016-01-15 14:07
So, wait. If I understood correctly, you has a `config.xml`:

``` xml
 <universal-links>
   <host name="www.blutdruckdaten.de" scheme="https">
    <path event="ULOpen" url="/lexikon.html" />
    <path event="ULOpen" url="/lexikon/*" />
    <path event="ULOpen" url="/chk*" />
    <path event="ULOpen" url="/del*" />
    <path event="ULOpen" url="/news.html" />
    <path event="ULOpen" url="/newsarchiv.html" />
    <path event="ULOpen" url="/news-en.html" />
    <path event="ULOpen" url="/newsarchive.html" />
  </host>
</universal-links>
```

Then in `index.js` you are trying to do like so:

``` js
  universalLinks.subscribe(null, function() {
    alert('alive')
  });
```

If so, then yes - that is not gonna work. If you have set `event` to the `<path />` component - then you need to provide this event name, when you subscribe:

``` js
universalLinks.subscribe('ULOpen', function() {
    alert('alive')
  });
```

**Comment by H0rst** [comment] 2016-01-15 14:25
X-) I missunderstood event name null is catching all events. I tried my event name before, but with the iOS problem i changed it to be sure, there is no error at this. Sorry.
You can close the issue, it is working now.

**Comment by nikDemyankov** [comment] 2016-01-15 14:35
> I missunderstood event name null is catching all events.

No, it captures all unnamed events :) Good that the problem is solved.

**Closed as completed by nikDemyankov** 2016-01-15 14:35 UTC
