### ISSUE TITLE
Event not fired when AndroidLaunchMode = singleTask or singleInstance

### ISSUE THREAD

**Issue by clemorphy** [nordnet/cordova-universal-links-plugin#85] opened 2016-09-12 16:46 UTC
When compiling with `AndroidLaunchMode`set to `singleTask`or `singleInstance`, if the app has not been launched, it is working. It launches the app and the event is fired.
But if the app has already been launched, it brings the app to foreground, but no event is fired in JS.

Am I missing something ?

I am testing on a Nexus 5 with Android 6.

**Comment by nikDemyankov** [comment] 2016-09-13 14:48
Sorry, a bit swamped with work right now. Will try to reproduce that tomorrow. For now my guess is that native side is not receiving launch intent when app is resumed. Which would be strange...

**Comment by clemorphy** [comment] 2016-09-15 01:04
Some news.
I have tested again today, rebuilding the app with `AndroidLaunchMode` set to `singleTask`, and guess what, now it works everytime! Even when the app is already launched, it brings it to foreground, and the JS event is fired.

I don't know what happened the previous times I tested it. I remember that I had rebuilt the app many times, and it was always failing, with `singleTask` or `singleInstance`... So I went back to `standard` mode.

But today I try `singleTask` again, and it works. I didn't change any other parameter.

Maybe that was a temporary problem on my Nexus 5.

**Comment by nikDemyankov** [comment] 2016-09-15 08:22
Could not reproduce it as well... Maybe you had some JS error on the page? Anyway, good, that it works now. Closing it, then. If you get this problem again - just reopen the issue.

**Closed as completed by nikDemyankov** 2016-09-15 08:22 UTC
